name: Deploy to Server
on:
  push:
    branches:
      - main  # 只有主分支有提交时才触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
